import { ethers } from 'ethers';
import { showToast } from './utils/helpers.js';

class ContractService {
    constructor() {
        this.provider = null;
        this.signer = null;
        this.contract = null;
        this.contractConfig = null;
        this.userAddress = null;
        
        // Event listeners
        this.onAccountChange = null;
    }

    async init() {
        try {
            // Fetch contract config generated by hardhat deployment script
            const response = await fetch('./js/contract-config.json');
            if (!response.ok) {
                console.warn('Contract config not found. Please deploy the contract first.');
                return false;
            }
            this.contractConfig = await response.json();
            
            // If MetaMask is present, setup provider but don't request accounts yet
            if (window.ethereum) {
                this.provider = new ethers.BrowserProvider(window.ethereum);
                
                // Handle account changes
                window.ethereum.on('accountsChanged', (accounts) => {
                    if (accounts.length > 0) {
                        this.userAddress = accounts[0];
                        this._setupContract(accounts[0]);
                    } else {
                        this.userAddress = null;
                        this.signer = null;
                        this.contract = null;
                    }
                    if (this.onAccountChange) this.onAccountChange(this.userAddress);
                });

                window.ethereum.on('chainChanged', () => {
                    window.location.reload();
                });
                
                // Check if already connected
                const accounts = await this.provider.listAccounts();
                if (accounts.length > 0) {
                    this.userAddress = accounts[0].address;
                    await this._setupContract(this.userAddress);
                }
            } else {
                console.warn('MetaMask not installed');
            }
            return true;
        } catch (error) {
            console.error('Error initializing contract service:', error);
            return false;
        }
    }

    async connectWallet() {
        if (!window.ethereum) {
            showToast('Please install MetaMask to use this dApp', 'error');
            return null;
        }

        try {
            // Force MetaMask to switch to the local Hardhat network (Chain ID: 31337 = 0x7A69)
            try {
                await window.ethereum.request({
                    method: 'wallet_switchEthereumChain',
                    params: [{ chainId: '0x7A69' }],
                });
            } catch (switchError) {
                // If the network is not added, add it automatically
                if (switchError.code === 4902) {
                    await window.ethereum.request({
                        method: 'wallet_addEthereumChain',
                        params: [{
                            chainId: '0x7A69',
                            chainName: 'Hardhat Local Network',
                            rpcUrls: ['http://127.0.0.1:8545'],
                            nativeCurrency: { name: 'ETH', symbol: 'ETH', decimals: 18 }
                        }]
                    });
                }
            }

            const accounts = await window.ethereum.request({ method: 'eth_requestAccounts' });
            this.userAddress = accounts[0];
            await this._setupContract(this.userAddress);
            if (this.onAccountChange) this.onAccountChange(this.userAddress);
            return this.userAddress;
        } catch (error) {
            console.error('Error connecting wallet:', error);
            showToast(error.message || 'Failed to connect wallet', 'error');
            return null;
        }
    }

    async _setupContract(address) {
        if (!this.provider || !this.contractConfig) return;
        this.signer = await this.provider.getSigner(address);
        this.contract = new ethers.Contract(
            this.contractConfig.address,
            this.contractConfig.abi,
            this.signer
        );
    }
    
    // Make a read-only call even if wallet is not connected
    async _getReadOnlyContract() {
        if (this.contract) return this.contract;
        if (!this.contractConfig) return null;
        
        // If metamask is not connected, use default provider to read
        let provider;
        if (window.ethereum) {
            provider = new ethers.BrowserProvider(window.ethereum);
        } else {
            provider = new ethers.JsonRpcProvider('http://127.0.0.1:8545'); // Hardhat default
        }
        return new ethers.Contract(this.contractConfig.address, this.contractConfig.abi, provider);
    }

    // ==========================================
    // ADMIN FUNCTIONS
    // ==========================================
    
    async registerUniversity(walletAddress, name, country) {
        if (!this.contract) throw new Error("Wallet not connected");
        try {
            const tx = await this.contract.registerUniversity(walletAddress, name, country);
            showToast('Transaction submitted. Waiting for confirmation...', 'info');
            const receipt = await tx.wait();
            showToast('University registered successfully!', 'success');
            return receipt;
        } catch (error) {
            console.error(error);
            showToast(error.reason || error.message || 'Registration failed', 'error');
            throw error;
        }
    }

    async deactivateUniversity(walletAddress) {
        if (!this.contract) throw new Error("Wallet not connected");
        try {
            const tx = await this.contract.deactivateUniversity(walletAddress);
            showToast('Transaction submitted...', 'info');
            await tx.wait();
            showToast('University deactivated!', 'success');
            return true;
        } catch (error) {
            console.error(error);
            showToast(error.reason || 'Failed to deactivate', 'error');
            throw error;
        }
    }

    // ==========================================
    // UNIVERSITY FUNCTIONS
    // ==========================================

    async registerStudent(studentId, name, email) {
        if (!this.contract) throw new Error("Wallet not connected");
        try {
            const tx = await this.contract.registerStudent(studentId, name, email);
            showToast('Transaction submitted...', 'info');
            await tx.wait();
            showToast('Student registered successfully!', 'success');
            return true;
        } catch (error) {
            console.error(error);
            showToast(error.reason || 'Failed to register student', 'error');
            throw error;
        }
    }

    async issueCertificate(certId, studentId, course, grade, ipfsHash) {
        if (!this.contract) throw new Error("Wallet not connected");
        try {
            const tx = await this.contract.issueCertificate(certId, studentId, course, grade, ipfsHash);
            showToast('Transaction submitted...', 'info');
            await tx.wait();
            showToast('Certificate issued securely on blockchain!', 'success');
            return true;
        } catch (error) {
            console.error(error);
            showToast(error.reason || 'Failed to issue certificate', 'error');
            throw error;
        }
    }

    async revokeCertificate(certId) {
        if (!this.contract) throw new Error("Wallet not connected");
        try {
            const tx = await this.contract.revokeCertificate(certId);
            showToast('Transaction submitted...', 'info');
            await tx.wait();
            showToast('Certificate revoked!', 'success');
            return true;
        } catch (error) {
            console.error(error);
            showToast(error.reason || 'Failed to revoke certificate', 'error');
            throw error;
        }
    }

    // ==========================================
    // READ FUNCTIONS (Public / Anyone)
    // ==========================================

    async verifyCertificate(certId) {
        const contract = await this._getReadOnlyContract();
        if (!contract) throw new Error("Contract not available");
        try {
            const result = await contract.verifyCertificate(certId);
            return {
                isValid: result.isValid,
                studentId: result.studentId,
                courseName: result.courseName,
                grade: result.grade,
                issuedBy: result.issuedBy,
                issuedAt: result.issuedAt.toString(),
                certHash: result.certHash
            };
        } catch (error) {
            if (error.message.includes("Certificate does not exist") || error.reason?.includes("Certificate does not exist")) {
                return null; // Not found
            }
            throw error;
        }
    }

    async getStats() {
        const contract = await this._getReadOnlyContract();
        if (!contract) return { universities: 0, students: 0, certificates: 0 };
        try {
            const [unis, students, certs] = await Promise.all([
                contract.getTotalUniversities(),
                contract.getTotalStudents(),
                contract.getTotalCertificates()
            ]);
            return {
                universities: Number(unis),
                students: Number(students),
                certificates: Number(certs)
            };
        } catch (e) {
            console.error("Error fetching stats:", e);
            return { universities: 0, students: 0, certificates: 0 };
        }
    }

    async getAllUniversities() {
        const contract = await this._getReadOnlyContract();
        if (!contract) return [];
        try {
            const addresses = await contract.getAllUniversityAddresses();
            const unis = [];
            for (let i = 0; i < addresses.length; i++) {
                const details = await contract.getUniversityDetails(addresses[i]);
                unis.push({
                    address: addresses[i],
                    name: details.name,
                    country: details.country,
                    isActive: details.isActive,
                    registeredAt: details.registeredAt.toString()
                });
            }
            return unis;
        } catch (e) {
            console.error("Error fetching universities:", e);
            return [];
        }
    }

    async getAllCertificates() {
        const contract = await this._getReadOnlyContract();
        if (!contract) return [];
        try {
            const certIds = await contract.getAllCertificateIds();
            const certs = [];
            // Fetching individually (in a real production app, we would use an indexer like TheGraph)
            for (let i = 0; i < Math.min(certIds.length, 50); i++) { // Limit to 50 for UI performance
                const details = await contract.getCertificateDetails(certIds[i]);
                certs.push({
                    certificateId: details.certificateId,
                    studentId: details.studentId,
                    courseName: details.courseName,
                    issuedBy: details.issuedBy,
                    issuedAt: details.issuedAt.toString(),
                    isValid: details.isValid
                });
            }
            return certs;
        } catch (e) {
            console.error("Error fetching certificates:", e);
            return [];
        }
    }

    // ==========================================
    // ROLE DETECTION & FILTERED DATA
    // ==========================================

    async getAdminAddress() {
        const contract = await this._getReadOnlyContract();
        if (!contract) return null;
        try {
            return await contract.admin();
        } catch (e) {
            console.error("Error fetching admin address:", e);
            return null;
        }
    }

    async isAdmin() {
        if (!this.userAddress) return false;
        const admin = await this.getAdminAddress();
        return admin && admin.toLowerCase() === this.userAddress.toLowerCase();
    }

    async isUniversity() {
        if (!this.userAddress) return false;
        const contract = await this._getReadOnlyContract();
        if (!contract) return false;
        try {
            const uni = await contract.universities(this.userAddress);
            return uni.isRegistered && uni.isActive;
        } catch (e) {
            return false;
        }
    }

    async getUniversityByAddress(address) {
        const contract = await this._getReadOnlyContract();
        if (!contract) return null;
        try {
            const uni = await contract.getUniversityDetails(address);
            return {
                name: uni.name,
                country: uni.country,
                walletAddress: uni.walletAddress,
                isRegistered: uni.isRegistered,
                isActive: uni.isActive,
                registeredAt: uni.registeredAt.toString()
            };
        } catch (e) {
            return null;
        }
    }

    async getStudentsByUniversity(universityAddress) {
        const contract = await this._getReadOnlyContract();
        if (!contract) return [];
        try {
            const allIds = await contract.getAllStudentIds();
            const students = [];
            for (let i = 0; i < allIds.length; i++) {
                const s = await contract.getStudentDetails(allIds[i]);
                if (s.universityAddress.toLowerCase() === universityAddress.toLowerCase()) {
                    students.push({
                        studentId: s.studentId,
                        name: s.name,
                        email: s.email,
                        universityAddress: s.universityAddress,
                        registeredAt: s.registeredAt.toString()
                    });
                }
            }
            return students;
        } catch (e) {
            console.error("Error fetching students by university:", e);
            return [];
        }
    }

    async getCertificatesByUniversity(universityAddress) {
        const contract = await this._getReadOnlyContract();
        if (!contract) return [];
        try {
            const allIds = await contract.getAllCertificateIds();
            const certs = [];
            for (let i = 0; i < allIds.length; i++) {
                const c = await contract.getCertificateDetails(allIds[i]);
                if (c.issuedBy.toLowerCase() === universityAddress.toLowerCase()) {
                    certs.push({
                        certificateId: c.certificateId,
                        studentId: c.studentId,
                        courseName: c.courseName,
                        grade: c.grade,
                        issuedBy: c.issuedBy,
                        issuedAt: c.issuedAt.toString(),
                        isValid: c.isValid,
                        isRevoked: c.isRevoked
                    });
                }
            }
            return certs;
        } catch (e) {
            console.error("Error fetching certificates by university:", e);
            return [];
        }
    }

    async getAllStudents() {
        const contract = await this._getReadOnlyContract();
        if (!contract) return [];
        try {
            const allIds = await contract.getAllStudentIds();
            const students = [];
            for (let i = 0; i < allIds.length; i++) {
                const s = await contract.getStudentDetails(allIds[i]);
                students.push({
                    studentId: s.studentId,
                    name: s.name,
                    email: s.email,
                    universityAddress: s.universityAddress,
                    registeredAt: s.registeredAt.toString()
                });
            }
            return students;
        } catch (e) {
            console.error("Error fetching all students:", e);
            return [];
        }
    }
}

// Export a singleton instance
const contractService = new ContractService();
export default contractService;
