export default {
    async render() {
        let metrics = null;
        let error = false;
        
        try {
            // Attempt to fetch performance metrics JSON generated by Hardhat script
            const response = await fetch('../../docs/performance-results.json');
            if (response.ok) {
                metrics = await response.json();
            } else {
                error = true;
            }
        } catch (e) {
            error = true;
        }

        if (error || !metrics) {
            return `
                <div class="animate-in">
                    <div class="empty-state">
                        <i class="fas fa-chart-line empty-icon text-warning"></i>
                        <h3 class="empty-title">Metrics Not Available</h3>
                        <p class="empty-text">Please run the performance evaluation script first:</p>
                        <code style="display: block; margin-top: 10px; background: var(--bg-card); padding: 10px; border-radius: var(--radius-sm); font-family: monospace;">cd blockchain && npx hardhat run scripts/performance-test.js</code>
                    </div>
                </div>
            `;
        }

        let html = `
            <div class="animate-in">
                <!-- Latency & Throughput Metrics -->
                <h3 class="mb-4" style="font-size: 18px;">Network Performance</h3>
                <div class="metric-grid">
                    <div class="metric-card">
                        <div class="metric-value">${metrics.throughput.tps}</div>
                        <div class="metric-label">Avg TPS</div>
                    </div>
                    <div class="metric-card">
                        <div class="metric-value">${metrics.blockConfirmation.avgMs} <span style="font-size: 14px; font-weight: normal; color: var(--text-muted);">ms</span></div>
                        <div class="metric-label">Block Confirmation</div>
                    </div>
                    <div class="metric-card">
                        <div class="metric-value">${metrics.issuanceLatency.avgMs} <span style="font-size: 14px; font-weight: normal; color: var(--text-muted);">ms</span></div>
                        <div class="metric-label">Issuance Latency</div>
                    </div>
                    <div class="metric-card">
                        <div class="metric-value">${metrics.verificationLatency.avgMs} <span style="font-size: 14px; font-weight: normal; color: var(--text-muted);">ms</span></div>
                        <div class="metric-label">Verification Latency</div>
                    </div>
                </div>

                <div class="grid-2 mt-6">
                    <!-- Gas Consumption Chart -->
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Gas Consumption by Function</h3>
                        </div>
                        <div class="card-body">
                            ${Object.entries(metrics.gasByFunction).map(([func, data]) => {
                                // Calculate width based on a reasonable max gas (e.g. 200k)
                                const percent = Math.min((parseInt(data.gasUsed) / 200000) * 100, 100);
                                return `
                                    <div class="chart-bar-container">
                                        <div class="chart-bar-label">
                                            <span>${func}</span>
                                            <span class="font-mono text-accent">${data.gasUsed} gas</span>
                                        </div>
                                        <div class="chart-bar-track">
                                            <div class="chart-bar-fill" style="width: ${percent}%;"></div>
                                        </div>
                                    </div>
                                `;
                            }).join('')}
                            
                            <div style="margin-top: 24px; padding-top: 16px; border-top: 1px solid var(--border-color); display: flex; justify-content: space-between;">
                                <span class="text-secondary font-weight-500">Contract Deployment Cost:</span>
                                <span class="font-mono text-warning">${metrics.deployment.gasUsed} gas (${metrics.deployment.costETH} ETH)</span>
                            </div>
                        </div>
                    </div>

                    <!-- Scalability Test -->
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Scalability Test (Batch Issuance)</h3>
                        </div>
                        <div class="card-body">
                            <div class="table-container">
                                <table class="data-table">
                                    <thead>
                                        <tr>
                                            <th>Volume (Certs)</th>
                                            <th>Time (sec)</th>
                                            <th>Throughput (TPS)</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        ${metrics.scalability.map(scale => `
                                            <tr>
                                                <td style="font-weight: 600; color: var(--accent-3);">${scale.volume}</td>
                                                <td>${scale.totalTimeSec}</td>
                                                <td class="text-success">${scale.tps}</td>
                                            </tr>
                                        `).join('')}
                                    </tbody>
                                </table>
                            </div>
                            
                            <div style="margin-top: 24px; padding: 16px; background: rgba(16, 185, 129, 0.1); border-radius: var(--radius-sm); border-left: 4px solid var(--accent-success);">
                                <div style="display: flex; justify-content: space-between; align-items: center;">
                                    <div>
                                        <h4 class="text-success" style="margin-bottom: 4px; font-size: 15px;">Reliability / Success Rate</h4>
                                        <p class="text-secondary" style="font-size: 13px;">Based on ${metrics.successRate.total} concurrent stress tests</p>
                                    </div>
                                    <div style="font-size: 28px; font-weight: 800; color: var(--accent-success);">${metrics.successRate.rate}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        `;

        return html;
    }
};
